var RDA = this.RDA || {};

RDA.Config = {
	API_URI : "http://localhost:5000",
	API_KEY : "U3DVW32BC431Y9IOIVXCSY212UIJH8",
	CLIENT_ID : "<YOUR_CLIENT_ID>",
	CLIENT_SECRET : "<YOUR_CLIENT_SECRET>",
	STORAGE_ID : "RDA_LOCALSTORAGE"
};
